In [1]:
import torch

__Ensuring that PyTorch is using GPU:__

In [2]:
torch.cuda.current_device()

0

In [3]:
torch.cuda.device_count()

1

In [4]:
torch.cuda.get_device_name(0)

'GeForce GTX 1080 Ti'

__Unline tensorflow, pytorch doesn't utilize the ENTIRE gpu memory, allocation is based on the need__

In [5]:
x = torch.empty(5, 3)
print(x) # near-zero values

tensor([[-2.0219e+38,  4.5558e-41, -2.0219e+38],
        [ 4.5558e-41,  1.4602e-19,  1.8617e+25],
        [ 1.1835e+22,  4.3066e+21,  6.3828e+28],
        [ 1.4603e-19,  1.1578e+27,  1.1362e+30],
        [ 7.1547e+22,  4.5828e+30,  1.2121e+04]])


In [6]:
x = torch.rand(3, 4) # random unif~[0,1]
print(x)

tensor([[0.1767, 0.3975, 0.7138, 0.4463],
        [0.5489, 0.7115, 0.3990, 0.6018],
        [0.8468, 0.3822, 0.1215, 0.3374]])


In [7]:
x = torch.zeros(5, 3, dtype=torch.long) # specify datatype , i.e., long
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


__List or array to torch tensor__

In [8]:
x = torch.tensor([[4.1, 2.3], [-1.8, 0.]], dtype=torch.float32)
print(x)

tensor([[ 4.1000,  2.3000],
        [-1.8000,  0.0000]])


In [9]:
x = x.new_ones(3, 4) # a new tensor of ones with the same datatype as x
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [10]:
x = x.new_full([3, 4], fill_value = 6.0)
print(x)

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


In [11]:
x = torch.rand_like(x) # random-unif, same dims and same datatype as x
print(x)

tensor([[0.2289, 0.9430, 0.8979, 0.2686],
        [0.1695, 0.7795, 0.0257, 0.4358],
        [0.6815, 0.5553, 0.3924, 0.0191]])


In [12]:
x.size()

torch.Size([3, 4])

In [13]:
x**2

tensor([[0.0524, 0.8893, 0.8063, 0.0722],
        [0.0287, 0.6076, 0.0007, 0.1899],
        [0.4644, 0.3084, 0.1540, 0.0004]])

In [14]:
x + x

tensor([[0.4579, 1.8861, 1.7959, 0.5373],
        [0.3390, 1.5589, 0.0514, 0.8716],
        [1.3629, 1.1107, 0.7849, 0.0383]])

In [15]:
y = torch.randn_like(x) # random normal
print(y)

tensor([[ 0.1310, -1.2842,  1.1554, -1.3247],
        [ 0.3521,  0.4458, -0.5820,  0.4713],
        [-0.7978, -0.9127, -0.4194, -0.6050]])


In [16]:
z = torch.add(x, y) 

In [17]:
z = x.add(y)

In [18]:
torch.add(x, y, out=z) # store output in tensor z
print(z)

tensor([[ 0.3599, -0.3411,  2.0534, -1.0560],
        [ 0.5216,  1.2253, -0.5563,  0.9072],
        [-0.1163, -0.3573, -0.0269, -0.5859]])


In [19]:
# in place addition - use understore '_'
y.add_(x) # y = y + x

tensor([[ 0.3599, -0.3411,  2.0534, -1.0560],
        [ 0.5216,  1.2253, -0.5563,  0.9072],
        [-0.1163, -0.3573, -0.0269, -0.5859]])

In [20]:
y

tensor([[ 0.3599, -0.3411,  2.0534, -1.0560],
        [ 0.5216,  1.2253, -0.5563,  0.9072],
        [-0.1163, -0.3573, -0.0269, -0.5859]])


__Resize/reshape tensor, using view__

In [21]:
x = torch.randn(4, 4)
x.size()

torch.Size([4, 4])

In [22]:
y = x.view([2, 8])
y.size()

torch.Size([2, 8])

In [23]:
z = x.view(-1, 16)  # the size -1 implies infer from other dimensions
z.size()

torch.Size([1, 16])

The Torch Tensor and NumPy array __will share their underlying memory locations, and changing one will change the other.__

In [24]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [25]:
b = a.numpy() # convert to numpy array
print(b)

[1. 1. 1. 1. 1.]


In [26]:
a.mul_(3.) # modify torch tensor 'a', both variables are modified
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [27]:
import numpy as np

In [28]:
a = np.ones(7)
a

array([1., 1., 1., 1., 1., 1., 1.])

In [29]:
b = torch.from_numpy(a) # from numpy to torch tensor
print(b)

tensor([1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)


In [30]:
c = torch.tensor(a) # this way of conversion doesnt correspond to shared memory locations

In [31]:
c.add_(3.5)
print(c)

tensor([4.5000, 4.5000, 4.5000, 4.5000, 4.5000, 4.5000, 4.5000], dtype=torch.float64)


In [32]:
print(a, b)

[1. 1. 1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)


### All the Tensors on the CPU

CUDA Tensors: Tensors can be moved onto any device using the `.to` method.

In [33]:
torch.cuda.is_available()

True

In [34]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    
    # create a tensor DIRECTLY on GPU
    y = torch.ones_like(x, device=device)  
    
    # OR just use strings ``.to("cuda")`` if you want to port to another device after creation 
    x = x.to(device)               
    
    z = x + y # z is by default on GPU
    
    print(z)
    
    # Transfer it to CPU 
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[ 2.1355,  0.8372, -0.3998, -0.2384],
        [ 1.7906,  0.5579,  2.0107,  0.9068],
        [ 0.7952,  1.4420,  1.3234, -0.7406],
        [-0.9798, -0.0655, -0.1357,  0.1003]], device='cuda:0')
tensor([[ 2.1355,  0.8372, -0.3998, -0.2384],
        [ 1.7906,  0.5579,  2.0107,  0.9068],
        [ 0.7952,  1.4420,  1.3234, -0.7406],
        [-0.9798, -0.0655, -0.1357,  0.1003]], dtype=torch.float64)


In [35]:
z.cpu() # on cpu

tensor([[ 2.1355,  0.8372, -0.3998, -0.2384],
        [ 1.7906,  0.5579,  2.0107,  0.9068],
        [ 0.7952,  1.4420,  1.3234, -0.7406],
        [-0.9798, -0.0655, -0.1357,  0.1003]])

In [36]:
z.cuda() # on gpu, 0 implies 1st GPU

tensor([[ 2.1355,  0.8372, -0.3998, -0.2384],
        [ 1.7906,  0.5579,  2.0107,  0.9068],
        [ 0.7952,  1.4420,  1.3234, -0.7406],
        [-0.9798, -0.0655, -0.1357,  0.1003]], device='cuda:0')

The __rank of a tensor__ refers to the number of dimensions present within the tensor.

In [38]:
len(z.size())

2